[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fmt]
line_length = 100
number_underscore = "thousands"

[rpc_endpoints]
eth = "https://eth.llamarpc.com"
arb = "https://arbitrum.llamarpc.com"
